before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./
    env:
      - CGO_ENABLED=1
    binary: midgard
    ldflags: 
      - -w -s -X main.VERSION={{.Version}}

    goos:
      - darwin

    goarch:
      - amd64
      - arm64

checksum:
  disable: true

upx:
  - enabled: true
  - compress: best

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

env_files:
  gitlab_token: ~/nope
  gitea_token: ~/nope