version: "3.7"
services:
  midgard-dev-service:
    container_name: midgard-dev-service
    build:
      context: ./
      dockerfile: ./ci/docker/Dockerfile.dev
    ports:
      - "8081:8081"
      - "8080:8080"
      - "8079:8079"
    env_file: ./ci/config/boilerplate/midgard.dev-env
    volumes:
      - ./:/app
    command:
      - air
      - --build.bin
      - "./tmp/main start -d -e -H 0.0.0.0"
