definitions:
  models.Cat:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      type:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /cats/{id}:
    get:
      consumes:
      - application/json
      description: get cat by ID
      operationId: get-string-by-string
      parameters:
      - description: cat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cat'
      summary: Show Cat
swagger: "2.0"
